[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/store"
  to = "/.netlify/functions/store"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200
  force = true

[[redirects]]
  from = "/api/image"
  to = "/.netlify/functions/image"
  status = 200
  force = true

[[redirects]]
  from = "/api/send-notification-email"
  to = "/.netlify/functions/send-notification-email"
  status = 200
  force = true
